# Generated by Django 4.1.7 on 2023-02-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
                (
                    "img",
                    models.CharField(
                        blank=True,
                        default="https://blog.tapptic.com/wp-content/uploads/2020/02/what-can-AI-generate-today-scaled.jpg",
                        max_length=400,
                    ),
                ),
            ],
        ),
    ]
